version: '3.7'

volumes:
    database:
    database-logs:
    database-backups:
    python-logs:

networks:
    legendhub:

services:
    mysql:
        build:
            context: ./mysql
        environment:
            - MYSQL_PORT=${MYSQL_PORT}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
        networks:
            - legendhub
        volumes:
            - database:/var/lib/mysql
            - database-logs:/var/log
            - database-backups:/backups
        tty: true
        restart: unless-stopped
    www:
        build:
            context: ./www
        depends_on:
            - mysql
        volumes:
            - type: bind
              source: ./www/src
              target: /app/src
        ports:
            - "${EXTERNAL_PORT}:${PORT}"
        environment:
            - PORT=${PORT}
            - NODE_ENV=${NODE_ENV}
            - MYSQL_PORT=${MYSQL_PORT}
            - MYSQL_HOST=mysql
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - GITHUB_TOKEN=${GITHUB_TOKEN}
            - GITHUB_REPOSITORY=${GITHUB_REPOSITORY}
            - RECAPTCHA_SITEKEY=${RECAPTCHA_SITEKEY}
            - RECAPTCHA_SECRET=${RECAPTCHA_SECRET}
        networks:
            - legendhub
        restart: unless-stopped
    python:
        build:
            context: ./python
        depends_on:
            - mysql
        environment:
            - MYSQL_PORT=${MYSQL_PORT}
            - MYSQL_HOST=mysql
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
        networks:
            - legendhub
        volumes:
            - python-logs:/var/log
        restart: unless-stopped
